### ISSUE TITLE
Review da Sprint 2

### ISSUE THREAD

**Issue by lucas-rtk** [opoze/eeduca-app#15]
Escrever uma retrospectiva do Sprint contendo:
O que foi bem?
O que não foi bem?
Que ações vamos fazer para melhorar?

**Comment by opoze** [comment]
Video criado e disponibilizado no seguinte endereço: https://www.youtube.com/watch?v=XxbAEg1ekdw

**Comment by opoze** [comment]
Apresento aqui uma retrospectiva do Sprint 2, conforme conversado na ferramenta Slack após a execução das tarefas:

O que foi bem?
Acertamos na definição dos papéis desde o início da sprint.
Cada aluno se comprometeu e fez o esperado.

O que não foi bem?
Não tivemos problemas.

O que vamos fazer para melhorar?
Adotar práticas de rituais apresentadas no general pela professora, deixando na wiki do projeto.
