### ISSUE TITLE
Criar persona - Aluno 1

### ISSUE THREAD

**Issue by lucas-rtk** [opoze/eeduca-app#3]

**Comment by rodrigogollo** [comment]
Criei duas Personas com suas respectivas Jornadas e Histórias de Usuário.

Segue os anexos.
[PERSONA1.docx](https://github.com/opoze/eeduca-app/files/4380701/PERSONA1.docx)
[PERSONA2.docx](https://github.com/opoze/eeduca-app/files/4380702/PERSONA2.docx)
