### ISSUE TITLE
Criar persona - Aluno 2

### ISSUE THREAD

**Issue by lucas-rtk** [opoze/eeduca-app#4]

**Comment by opoze** [comment]
## Persona Samanta
**Nome**: Samanta
**Perfil:**
- 24 anos
- Solteira
- Tester
- YouTuber
- Mora com pais

**Comportamento:**
- Apressada
- Impaciente
- Minimalista
- Gasta tudo que ganha
- Aficionada por produtos de beleza
- Não gosta de ficar em casa

**Necessidades:**
- Limpeza
- Sair
- Organização
- Postar videos todos os dias

**Comment by opoze** [comment]
### Histórias do Usuário
Como uma usuária do aplicativo
Eu quero saber se o professor me deu falta na aula passada
Para poder encaminhar um comprovante de falta

Como uma usuária do aplicativo
Eu quero pode ver ser o professor deixou aviso sobre a aula adiada por causa do corona virus
Para saber como proceder

**Comment by opoze** [comment]
### Jornada do usuário
- Acorda tarde
- Se atualiza sobre as visualizações de seus videos
- Limpa a casa
- Almoça sempre com pressa
- Vai para o estágio
- Reclama do trabalho que não terá tempo
- Passa o dia com testes e detalhes pequenos a incomodam
- A tarde se prepara para o turno noturno de aula
- Acessa o aplicativo Eeduca
- Enxerga e comenta os problemas do  app
- Faz login
- Pesquisa suas turmas
- Acessa a sua turma
- Confere se o professor deixou avisos, materiais, sempre em cima da hora
- Verifica se recebeu falta na aula passada que não compareceu
- Manda  uma mensagem para a professora com um atestado para justificar a falta
- Vai to trabalho até a escola visualizando se a professora responde sua justificativa
